twitter-app/config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  
  get 'profile' => 'static_pages#profile'
  get 'messages' => 'static_pages#messages'
  get 'users' => 'users#index'

end

twitter-app/app/models/user.rb
class User < ActiveRecord::Base

end

twitter-app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  ## Serving a view
  def home
  end

  def profile
  end

  def messages
  end

end

twitter-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

twitter-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Profile", profile_path %></li>
    <li><%= link_to "Messages", messages_path %></li>
    <li><%= link_to "Users", users_path %></li>
  </ul>
</div>

<%= yield %>

</body>
</html>

twitter-app/app/views/static_pages/home.html.erb
<h1>Twitter App</h1>

<p>Hello World!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas malesuada augue nulla, id varius elit volutpat et. Nam facilisis porta aliquam. Proin iaculis sollicitudin pretium. Praesent eu libero sit amet mi ullamcorper tincidunt nec eu sapien. Maecenas elementum pretium felis, ac pellentesque nisi interdum vitae.</p>

twitter-app/app/views/static_pages/messages.html.erb
<h2>Messages</h2>

twitter-app/app/views/static_pages/profile.html.erb
<h2>This is my profile</h2>

twitter-app/app/views/users/index.html.erb
<h2>These are all the users</h2>

<h3>Users:</h3>

<% @users.each do |user| %>  
  <div><%= user.username %>: <%= user.password %></div>
<% end %>