ecommerce_app/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'about' => 'about#index'

  get 'store' => 'store#index'
  get 'store/:id' => 'store#view'

  get 'store/:id/products' => 'products#index'

end

ecommerce_app/app/models/product.rb
class Product < ActiveRecord::Base
end

ecommerce_app/app/models/store.rb
class Store < ActiveRecord::Base
  attr_accessor :store_name

  $store_list = []

  def new_store(store_name)
    Store.new(store_name)
    
    $store_list.push({store_name: store_name})
  end
end

ecommerce_app/app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end

end

ecommerce_app/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
  end

end

ecommerce_app/app/controllers/store_controller.rb
class StoreController < ApplicationController

  def index
  end

  def show
  end

end

ecommerce_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

ecommerce_app/app/views/about/index.html.erb
<h2> About my store</h2>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan ligula dolor, vitae faucibus ex consectetur in. Suspendisse facilisis est a lectus tempor, at cursus arcu tincidunt. Suspendisse turpis tortor, rutrum at congue vitae, egestas ac nisl. Aliquam ac nisl lorem. Curabitur non eros gravida, tincidunt justo a, porttitor velit. Sed sit amet sapien eros. Praesent ac tortor blandit, dapibus sapien a, bibendum magna. Nullam a odio ac tellus auctor tincidunt sed vel nulla. Nullam ut dui pellentesque, porttitor quam eget, cursus odio. Vestibulum faucibus mollis nulla ut auctor.</p>

<p>Praesent tincidunt arcu id laoreet fringilla. Sed ut scelerisque augue. Donec ac tristique nisi. Nam tincidunt condimentum turpis, ac euismod turpis mattis et. Donec ullamcorper tincidunt volutpat. Praesent a libero enim. Morbi tellus augue, commodo eu urna vel, efficitur mollis risus. Sed finibus suscipit libero vel sagittis. Donec pharetra urna eget ante fermentum varius. Fusce in varius risus. Integer dignissim facilisis mi sodales finibus. Nam posuere porttitor ante a pellentesque.</p>

ecommerce_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EcommerceApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <header>
    <h1>Ecommerce Store</h2>

    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Store", store_path %></li>
      </ul>
    </nav>
  </header>

  <%= yield %>
</div>

</body>
</html>

ecommerce_app/app/views/welcome/index.html.erb
<h3> Home Page </h3>